language: generic
sudo: required
services: 
  - docker

before_install: 
  - docker build -t tooth1234/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tooth1234/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-778662752595"
  bucket_path: "docker"
  on: 
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secrect_access_key: "$AWS_SECRET_KEY"